blank_issues_enabled: false
contact_links:
  - name: 🤚 GitHub Discussions
    url: https://github.com/lvyuemeng/pulith/discussions
    about: If your issue is not a feature or bug, go to the discussion panel and retrieve if your issue already exists before submitting it.